export enum Data {
    SheetName = 'Data',
    TestCase_ID_ColumnIndex = 0,
    TestCase_Title_ColumnIndex = 1,
    FirstName_ColumnIndex = 2,
    LastName_ColumnIndex = 3,
    Email_ColumnIndex = 4,
    Gender_ColumnIndex = 5,
    Mobile_ColumnIndex = 6,
    DateOfBirth_ColumnIndex = 7,
    Subjects_ColumnIndex = 8,
    Hobbies_ColumnIndex = 9,
    Picture_ColumnIndex = 10,
    Address_ColumnIndex = 11,
    State_ColumnIndex = 12,
    City_ColumnIndex = 13,
    ExpectedResult_ColumnIndex = 14,
}