name: Playwright Tests

on:
  push:
    branches: [ features/v1, main ]
  pull_request:
    branches: [ features/v1, main ]

permissions:
  contents: write

env:
  env: qa

jobs:
  api-testing:
    name: 🧪 Run API Tests
    runs-on: ubuntu-latest
    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }} # Removed or comment out if not defined
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }} # Uncomment if PASSWORD secret is defined in repository settings

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧱 Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start mock api server
        run: |
          if [ -z "${{ secrets.AUTH_TOKEN }}" ]; then
            echo "AUTH_TOKEN is not defined"
            exit 1
          fi
          if [ -z "${{ secrets.USERNAME }}" ]; then
            echo "USERNAME is not defined"
            exit 1
          fi
          if [ -z "${{ secrets.PASSWORD }}" ]; then
            echo "PASSWORD is not defined"
            exit 1
          fi

          echo "Starting mock API server from script..."
          chmod +x setups/start-mock-api.sh
          ./setups/start-mock-api.sh &
          sleep 2 # Wait for the server to start

      - name: ▶️ Run API tests
        run: |
          echo "Running API tests on environment: ${{ env.env }}"
          if [ -z "${{ env.env }}" ]; then
            echo "Environment variable 'env' is not set. Defaulting to 'dev'."
            export env=dev
          fi
          ENV=${{ env.env }} npx playwright test tests/api --project=api || true
          echo "API tests completed."

      - name: 📤 Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-api
          path: allure-results
          if-no-files-found: warn    

  ui-testing:
    name: 🧪 Run UI Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        shard: [1/2, 2/2]

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧱 Install Playwright browsers
        run: npx playwright install --with-deps

      - name: ▶️ Run Playwright tests on UI
        run: |
          echo "Running UI tests on browser: ${{ matrix.browser }} and environment: ${{ env.env }}"
          if [ -z "${{ env.env }}" ]; then
            echo "Environment variable 'env' is not set. Defaulting to 'dev'."
            export env=dev
          fi
          ENV=${{ env.env }} npx playwright test tests/form --project=${{ matrix.browser }} --shard=${{ matrix.shard }} || true
          echo "Playwright tests completed."

      - name: 📤 Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results
          if-no-files-found: warn

  merge:
    name: 🏗️ Merge Allure Results
    needs: [ui-testing, api-testing]
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Download Chromium Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-chromium
          path: ./merged-results
        continue-on-error: true

      - name: ⬇️ Download Firefox Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-firefox
          path: ./merged-results
        continue-on-error: true    

      - name: ⬇️ Download Webkit Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-webkit
          path: ./merged-results
        continue-on-error: true
        
      - name: ⬇️ Download API Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-api
          path: ./merged-results
        continue-on-error: true  

      - name: 📤 Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: merged-results
          path: merged-results
          if-no-files-found: warn    

  publish:
    name: 🚀 Publish Allure Report
    needs: merge
    runs-on: ubuntu-latest

    steps:

      # - name: Create dummy history
      #   run: |
      #     mkdir -p allure-report/history
      #     echo "test" > allure-report/history/history.txt

      # - name: Upload Allure History
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: allure-history
      #     path: allure-report/history

      # - name: Download Allure History
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: allure-history
      #     path: allure-history
      #   continue-on-error: true  

      # - name: List files
      #   run: ls -R allure-history

      - name: Download Allure History
        uses: actions/download-artifact@v4
        with:
          name: allure-history
          path: allure-history
        continue-on-error: true

      - name: ⬇️ Download Allure Results Artifact
        uses: actions/download-artifact@v4
        with:
          name: merged-results
          path: merged-results

      - name: ♻️ Copy Allure history
        run: |
          echo "Checking existence of allure-history and merged-results..."
    
          if [ -d "allure-history" ]; then
            echo "✅ Directory 'allure-history' exists."
          else
            echo "❌ Directory 'allure-history' does NOT exist."
          fi

          if [ -d "merged-results" ]; then
            echo "✅ Directory 'merged-results' exists."
          else
            echo "❌ Directory 'merged-results' does NOT exist."
          fi

          if [ -d "allure-history" ] && [ -d "merged-results" ]; then
            echo "📂 Copying history into merged-results..."
            mkdir -p merged-results/history
            cp -r allure-history/* merged-results/history
          else
            echo "No previous allure-history found. Skipping history copy."  
          fi
          
      - name: 📊 Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: |
          rm -rf allure-report
          allure generate ./merged-results -o allure-report --clean

      # - name: 📦 Upload Allure Report Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: allure-report
      #     path: allure-report
      #     retention-days: 5

      - name: Upload Allure History
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: allure-report/history

      - name: 📤 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages       
       
