name: Playwright Tests

on:
  push:
    branches: [ features/v1, main ]
  pull_request:
    branches: [ features/v1, main ]

permissions:
  contents: write

env:
  env: qa

jobs:

  # install:
  #   name: 🧩 Install Dependencies
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: ⬇️ Checkout code
  #       uses: actions/checkout@v3

  #     - name: 🟢 Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20

  #     - name: 📦 Install dependencies
  #       run: npm ci

  #     - name: 🧱 Install Playwright browsers
  #       run: npx playwright install --with-deps
          
  #     - name: 📊 Install Allure CLI
  #       run: npm install -g allure-commandline  
    
  api-testing:
    name: 🧪 Run API Tests
    runs-on: ubuntu-latest
    # needs: install
    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }} # Removed or comment out if not defined
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }} # Uncomment if PASSWORD secret is defined in repository settings

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧱 Install Playwright browsers
        run: npx playwright install --with-deps
          
      - name: 📊 Install Allure CLI
        run: npm install -g allure-commandline  

      - name: 🔍 Debug — List files
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "List of files in current directory:"
          find . -type f

      - name: Start mock api server
        run: |
          if [ -z "${{ secrets.AUTH_TOKEN }}" ]; then
            echo "AUTH_TOKEN is not defined"
            exit 1
          fi
          if [ -z "${{ secrets.USERNAME }}" ]; then
            echo "USERNAME is not defined"
            exit 1
          fi
          if [ -z "${{ secrets.PASSWORD }}" ]; then
            echo "PASSWORD is not defined"
            exit 1
          fi

          echo "Starting mock API server from script..."
          chmod +x setups/start-mock-api.sh
          ./setups/start-mock-api.sh &
          sleep 2 # Wait for the server to start

      - name: ▶️ Run API tests
        run: |
          echo "Running API tests on environment: ${{ env.env }}"
          if [ -z "${{ env.env }}" ]; then
            echo "Environment variable 'env' is not set. Defaulting to 'dev'."
            export env=dev
          fi
          ENV=${{ env.env }} npx playwright test tests/api
          echo "API tests completed."

      - name: 📤 Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-api
          path: allure-results
          if-no-files-found: warn    

  ui-testing:
    name: 🧪 Run UI Testing
    runs-on: ubuntu-latest
    # needs: install
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧱 Install Playwright browsers
        run: npx playwright install --with-deps
          
      - name: 📊 Install Allure CLI
        run: npm install -g allure-commandline

      - name: ▶️ Run Playwright tests on UI
        run: |
          echo "Running UI tests on browser: ${{ matrix.browser }} and environment: ${{ env.env }}"
          if [ -z "${{ env.env }}" ]; then
            echo "Environment variable 'env' is not set. Defaulting to 'dev'."
            export env=dev
          fi
          ENV=${{ env.env }} npx playwright test tests/form --project=${{ matrix.browser }} || true
          echo "Playwright tests completed."

      # - name: 📁 Check Allure Results ${{ matrix.browser }}
      #   if: always()
      #   run: |
      #     echo "Checking allure-results-${{ matrix.browser }}..."
      #     ls -la
      #     ls -la allure-results-${{ matrix.browser }} || echo "❌ No allure-results-${{ matrix.browser }} directory"

      - name: 📤 Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results
          if-no-files-found: warn

  merge:
    name: 🏗️ Merge Allure Results
    needs: [ui-testing, api-testing]
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Download Chromium Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-chromium
          path: ./merged-results
        continue-on-error: true

      - name: ⬇️ Download Firefox Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-firefox
          path: ./merged-results
        continue-on-error: true    

      - name: ⬇️ Download Webkit Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-webkit
          path: ./merged-results
        continue-on-error: true
        
      - name: ⬇️ Download Webkit Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-api
          path: ./merged-results
        continue-on-error: true  

      - name: 📤 Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: merged-results
          path: merged-results
          if-no-files-found: warn    

  publish:
    name: 🚀 Publish Allure Report
    needs: merge
    runs-on: ubuntu-latest

    steps:
      - name: Download Allure History
        uses: actions/download-artifact@v4
        with:
          name: allure-history
          path: allure-history
        continue-on-error: true

      - name: ⬇️ Download Allure Results Artifact
        uses: actions/download-artifact@v4
        with:
          name: merged-results
          path: merged-results  

      - name: ♻️ Copy Allure history
        run: |
          if [ -d "allure-history" ] && [ -d "merged-results" ]; then
            cp -r allure-history/* merged-results/history
          fi

      - name: Generate Allure Report
        run: |
          rm -rf allure-report
          npx allure generate ./merged-results -o allure-report

      - name: 📦 Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 5

      - name: Upload Allure History
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: allure-report/history

      - name: 📤 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages       
       
